-- Fraud Detection Demo: Database Setup
-- This script creates the schema and tables for the Intelligent Fraud Detection Agent

CREATE DATABASE IF NOT EXISTS FRAUD_DETECTION_DEMO;
CREATE SCHEMA IF NOT EXISTS FRAUD_DETECTION_DEMO.ANALYTICS;

-- Customer profiles with spending patterns
CREATE OR REPLACE TABLE FRAUD_DETECTION_DEMO.ANALYTICS.CUSTOMERS (
    CUSTOMER_ID VARCHAR(20) PRIMARY KEY,
    FULL_NAME VARCHAR(100),
    EMAIL VARCHAR(150),
    PHONE VARCHAR(20),
    COUNTRY VARCHAR(50),
    CITY VARCHAR(50),
    ACCOUNT_OPEN_DATE DATE,
    RISK_TIER VARCHAR(10),
    AVG_MONTHLY_SPEND DECIMAL(12,2),
    AVG_TRANSACTION_AMOUNT DECIMAL(10,2),
    TYPICAL_CHANNEL VARCHAR(20),
    IS_VERIFIED BOOLEAN,
    LAST_LOGIN TIMESTAMP_NTZ
);

-- Merchant risk profiles
CREATE OR REPLACE TABLE FRAUD_DETECTION_DEMO.ANALYTICS.MERCHANT_PROFILES (
    MERCHANT_ID VARCHAR(20) PRIMARY KEY,
    MERCHANT_NAME VARCHAR(100),
    MCC_CODE VARCHAR(10),
    MCC_CATEGORY VARCHAR(50),
    RISK_CATEGORY VARCHAR(15),
    COUNTRY VARCHAR(50),
    CITY VARCHAR(50),
    AVG_TRANSACTION_SIZE DECIMAL(10,2),
    FRAUD_RATE_HISTORICAL DECIMAL(5,4),
    IS_ONLINE BOOLEAN
);

-- Transaction ledger
CREATE OR REPLACE TABLE FRAUD_DETECTION_DEMO.ANALYTICS.TRANSACTIONS (
    TRANSACTION_ID VARCHAR(30) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(20),
    MERCHANT_ID VARCHAR(20),
    AMOUNT DECIMAL(12,2),
    CURRENCY VARCHAR(3),
    TRANSACTION_TIME TIMESTAMP_NTZ,
    CHANNEL VARCHAR(20),
    CARD_PRESENT BOOLEAN,
    COUNTRY VARCHAR(50),
    CITY VARCHAR(50),
    DEVICE_TYPE VARCHAR(20),
    IP_ADDRESS VARCHAR(45),
    STATUS VARCHAR(15),
    IS_FRAUD_LABEL BOOLEAN
);

-- Fraud alert output table (agent writes decisions here)
CREATE OR REPLACE TABLE FRAUD_DETECTION_DEMO.ANALYTICS.FRAUD_ALERTS (
    ALERT_ID VARCHAR(30) PRIMARY KEY,
    TRANSACTION_ID VARCHAR(30),
    CUSTOMER_ID VARCHAR(20),
    DETECTION_TIME TIMESTAMP_NTZ,
    ANOMALY_TYPE VARCHAR(50),
    RISK_SCORE INTEGER,
    RISK_LEVEL VARCHAR(10),
    REASONING TEXT,
    ACTION_TAKEN VARCHAR(30),
    REVIEWED_BY VARCHAR(50),
    REVIEW_TIME TIMESTAMP_NTZ,
    STATUS VARCHAR(15) DEFAULT 'OPEN'
);
